### PR TITLE
Less bright text

### PR DESCRIPTION
**Pull request by RUSshy**
I don't really like most "dark themes" because they only just put WHITE text over BLACK bg  , wich is bad because the contrast is way too high and hurts way more the eyes (in my opinion)

So a more gray/yellowish white is usually prefered :D

### CODE REVIEW

**Comment by RUSshy** [comment]
I'm not sure if i can see difference but i really have no idea how to do CSS stuff so i tried xD

**Comment by RUSshy** [comment]
This dark theme is imo the best one, bg isn't black, and text is not white 

https://userstyles.org/styles/37035/github-dark

37035_after

**Comment by widget-** [comment]
There's a larger and more comprehensive theme at [laCour/slack-night-mode](https://github.com/laCour/slack-night-mode). It looks like it's closer to what you want.

Otherwise I have plans to add theme variants (including a grey one) but that's later after I refactor all the CSS into Less.

**Comment by widget-** [comment]
@RUSshy, I added instructions for changing the CSS colors on top of this theme. Give it a look and tell me if it meets your needs for now.

**Comment by widget-** [comment]
Closing this as I believe I've addressed the issue. Let me know if you have any concerns.

**Pull request closed without merging**
